[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino

board_build.partitions = no_ota.csv

upload_speed = 921600
monitor_speed = 115200

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue

lib_deps =
    adafruit/RTClib@^2.0.4
    esphome/ESP32-audioI2S@^2.0.7
    
lib_extra_dirs = lib
