[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

; Конфигурация для 8MB флеш-памяти
board_build.partitions = huge_app.csv

build_flags =
  -D USER_SETUP_LOADED=1
  -include lib/TFT_eSPI/User_Setups/Setup_GC9A01.h
  -D BOARD_HAS_PSRAM
  -D USE_PSRAM
  -mfix-esp32-psram-cache-issue
  -Os
  -D CORE_DEBUG_LEVEL=0  ; Уменьшаем отладочную информацию

; Оптимизация для уменьшения размера
build_unflags = 
  -Os
  -ggdb

; Оптимизация компилятора
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

lib_deps =
    bodmer/TFT_eSPI@^2.5.32
    esphome/ESP32-audioI2S@^2.0.7
    bblanchon/ArduinoJson@^6.21.4

lib_extra_dirs = lib

; Оптимизация размера
build_type = release
